name: Deploy Wyn's MyFort Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: verlyn13/kids-deploy-actions/.github/workflows/deploy.yml@main
    with:
      build_command: 'npm install && npm run build'   # now has a robust build
      build_output_dir: 'dist'                         # deploy built files from 'dist'
      remote_target_dir: '/var/www/kidsites/wyn'      # target directory on the server
    secrets: inherit
    permissions:
      actions: read
      contents: read
